//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.14 at 12:11:37 PM MESZ 
//


package jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Spieler" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Anzeigename" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Telefonnummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "spieler"
})
@XmlRootElement(name = "Accountliste")
public class Accountliste {

    @XmlElement(name = "Spieler", required = true)
    protected List<Accountliste.Spieler> spieler;

    /**
     * Gets the value of the spieler property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spieler property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpieler().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Accountliste.Spieler }
     * 
     * 
     */
    public List<Accountliste.Spieler> getSpieler() {
        if (spieler == null) {
            spieler = new ArrayList<Accountliste.Spieler>();
        }
        return this.spieler;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Anzeigename" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Telefonnummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "anzeigename",
        "telefonnummer"
    })
    public static class Spieler {

        @XmlElement(name = "Anzeigename", required = true)
        protected String anzeigename;
        @XmlElement(name = "Telefonnummer", required = true)
        protected String telefonnummer;

        /**
         * Gets the value of the anzeigename property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAnzeigename() {
            return anzeigename;
        }

        /**
         * Sets the value of the anzeigename property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAnzeigename(String value) {
            this.anzeigename = value;
        }

        /**
         * Gets the value of the telefonnummer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTelefonnummer() {
            return telefonnummer;
        }

        /**
         * Sets the value of the telefonnummer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTelefonnummer(String value) {
            this.telefonnummer = value;
        }

    }

}
