//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.21 at 11:53:42 AM MESZ 
//


package jaxb;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="event" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Event-ID" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                   &lt;element name="Spielzeitraum">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="von" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="bis" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="min.Spieler" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                   &lt;element name="max.Spieler" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                   &lt;element name="Sportart">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Fu§ball"/>
 *                         &lt;enumeration value="Basketball"/>
 *                         &lt;enumeration value="Tennis"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Oertlichkeit">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Ort-ID" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                             &lt;element name="Ort" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Platz" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="min.Spieleranzahl" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                             &lt;element name="max.Spieleranzahl" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                             &lt;element name="Oeffnungszeiten">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="geoeffnet_von" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *                                       &lt;element name="geoeffnet_bis" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *                                       &lt;element name="geschlossen_an" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Preis">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                   &lt;minInclusive value="0"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Spielerliste">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Spieler" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Anzeigename" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Telefonnummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Backlist">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Spieler" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Anzeigename" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Telefonnummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Admin">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Anzeigename" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Telefonnummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="subAdmin" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "event"
})
@XmlRootElement(name = "Events")
public class Events {

    @XmlElement(required = true)
    protected List<Events.Event> event;

    /**
     * Gets the value of the event property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the event property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Events.Event }
     * 
     * 
     */
    public List<Events.Event> getEvent() {
        if (event == null) {
            event = new ArrayList<Events.Event>();
        }
        return this.event;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Event-ID" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *         &lt;element name="Spielzeitraum">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="von" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="bis" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="min.Spieler" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *         &lt;element name="max.Spieler" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *         &lt;element name="Sportart">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Fu§ball"/>
     *               &lt;enumeration value="Basketball"/>
     *               &lt;enumeration value="Tennis"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Oertlichkeit">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Ort-ID" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *                   &lt;element name="Ort" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Platz" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="min.Spieleranzahl" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *                   &lt;element name="max.Spieleranzahl" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *                   &lt;element name="Oeffnungszeiten">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="geoeffnet_von" type="{http://www.w3.org/2001/XMLSchema}time"/>
     *                             &lt;element name="geoeffnet_bis" type="{http://www.w3.org/2001/XMLSchema}time"/>
     *                             &lt;element name="geschlossen_an" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Preis">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                         &lt;minInclusive value="0"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Spielerliste">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Spieler" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Anzeigename" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Telefonnummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Backlist">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Spieler" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Anzeigename" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Telefonnummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Admin">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Anzeigename" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Telefonnummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="subAdmin" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "eventID",
        "spielzeitraum",
        "minSpieler",
        "maxSpieler",
        "sportart",
        "oertlichkeit",
        "spielerliste",
        "backlist",
        "admin"
    })
    public static class Event {

        @XmlElement(name = "Event-ID", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger eventID;
        @XmlElement(name = "Spielzeitraum", required = true)
        protected Events.Event.Spielzeitraum spielzeitraum;
        @XmlElement(name = "min.Spieler", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger minSpieler;
        @XmlElement(name = "max.Spieler", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger maxSpieler;
        @XmlElement(name = "Sportart", required = true)
        protected String sportart;
        @XmlElement(name = "Oertlichkeit", required = true)
        protected Events.Event.Oertlichkeit oertlichkeit;
        @XmlElement(name = "Spielerliste", required = true)
        protected Events.Event.Spielerliste spielerliste;
        @XmlElement(name = "Backlist", required = true)
        protected Events.Event.Backlist backlist;
        @XmlElement(name = "Admin", required = true)
        protected Events.Event.Admin admin;

        /**
         * Gets the value of the eventID property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getEventID() {
            return eventID;
        }

        /**
         * Sets the value of the eventID property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setEventID(BigInteger value) {
            this.eventID = value;
        }

        /**
         * Gets the value of the spielzeitraum property.
         * 
         * @return
         *     possible object is
         *     {@link Events.Event.Spielzeitraum }
         *     
         */
        public Events.Event.Spielzeitraum getSpielzeitraum() {
            return spielzeitraum;
        }

        /**
         * Sets the value of the spielzeitraum property.
         * 
         * @param value
         *     allowed object is
         *     {@link Events.Event.Spielzeitraum }
         *     
         */
        public void setSpielzeitraum(Events.Event.Spielzeitraum value) {
            this.spielzeitraum = value;
        }

        /**
         * Gets the value of the minSpieler property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getMinSpieler() {
            return minSpieler;
        }

        /**
         * Sets the value of the minSpieler property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setMinSpieler(BigInteger value) {
            this.minSpieler = value;
        }

        /**
         * Gets the value of the maxSpieler property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getMaxSpieler() {
            return maxSpieler;
        }

        /**
         * Sets the value of the maxSpieler property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setMaxSpieler(BigInteger value) {
            this.maxSpieler = value;
        }

        /**
         * Gets the value of the sportart property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSportart() {
            return sportart;
        }

        /**
         * Sets the value of the sportart property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSportart(String value) {
            this.sportart = value;
        }

        /**
         * Gets the value of the oertlichkeit property.
         * 
         * @return
         *     possible object is
         *     {@link Events.Event.Oertlichkeit }
         *     
         */
        public Events.Event.Oertlichkeit getOertlichkeit() {
            return oertlichkeit;
        }

        /**
         * Sets the value of the oertlichkeit property.
         * 
         * @param value
         *     allowed object is
         *     {@link Events.Event.Oertlichkeit }
         *     
         */
        public void setOertlichkeit(Events.Event.Oertlichkeit value) {
            this.oertlichkeit = value;
        }

        /**
         * Gets the value of the spielerliste property.
         * 
         * @return
         *     possible object is
         *     {@link Events.Event.Spielerliste }
         *     
         */
        public Events.Event.Spielerliste getSpielerliste() {
            return spielerliste;
        }

        /**
         * Sets the value of the spielerliste property.
         * 
         * @param value
         *     allowed object is
         *     {@link Events.Event.Spielerliste }
         *     
         */
        public void setSpielerliste(Events.Event.Spielerliste value) {
            this.spielerliste = value;
        }

        /**
         * Gets the value of the backlist property.
         * 
         * @return
         *     possible object is
         *     {@link Events.Event.Backlist }
         *     
         */
        public Events.Event.Backlist getBacklist() {
            return backlist;
        }

        /**
         * Sets the value of the backlist property.
         * 
         * @param value
         *     allowed object is
         *     {@link Events.Event.Backlist }
         *     
         */
        public void setBacklist(Events.Event.Backlist value) {
            this.backlist = value;
        }

        /**
         * Gets the value of the admin property.
         * 
         * @return
         *     possible object is
         *     {@link Events.Event.Admin }
         *     
         */
        public Events.Event.Admin getAdmin() {
            return admin;
        }

        /**
         * Sets the value of the admin property.
         * 
         * @param value
         *     allowed object is
         *     {@link Events.Event.Admin }
         *     
         */
        public void setAdmin(Events.Event.Admin value) {
            this.admin = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Anzeigename" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Telefonnummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="subAdmin" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "anzeigename",
            "telefonnummer"
        })
        public static class Admin {

            @XmlElement(name = "Anzeigename", required = true)
            protected String anzeigename;
            @XmlElement(name = "Telefonnummer", required = true)
            protected String telefonnummer;
            @XmlAttribute
            protected Boolean subAdmin;

            /**
             * Gets the value of the anzeigename property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAnzeigename() {
                return anzeigename;
            }

            /**
             * Sets the value of the anzeigename property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAnzeigename(String value) {
                this.anzeigename = value;
            }

            /**
             * Gets the value of the telefonnummer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTelefonnummer() {
                return telefonnummer;
            }

            /**
             * Sets the value of the telefonnummer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTelefonnummer(String value) {
                this.telefonnummer = value;
            }

            /**
             * Gets the value of the subAdmin property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isSubAdmin() {
                return subAdmin;
            }

            /**
             * Sets the value of the subAdmin property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setSubAdmin(Boolean value) {
                this.subAdmin = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Spieler" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Anzeigename" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Telefonnummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "spieler"
        })
        public static class Backlist {

            @XmlElement(name = "Spieler", required = true)
            protected List<Events.Event.Backlist.Spieler> spieler;

            /**
             * Gets the value of the spieler property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the spieler property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSpieler().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Events.Event.Backlist.Spieler }
             * 
             * 
             */
            public List<Events.Event.Backlist.Spieler> getSpieler() {
                if (spieler == null) {
                    spieler = new ArrayList<Events.Event.Backlist.Spieler>();
                }
                return this.spieler;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Anzeigename" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Telefonnummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "anzeigename",
                "telefonnummer"
            })
            public static class Spieler {

                @XmlElement(name = "Anzeigename", required = true)
                protected String anzeigename;
                @XmlElement(name = "Telefonnummer", required = true)
                protected String telefonnummer;

                /**
                 * Gets the value of the anzeigename property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAnzeigename() {
                    return anzeigename;
                }

                /**
                 * Sets the value of the anzeigename property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAnzeigename(String value) {
                    this.anzeigename = value;
                }

                /**
                 * Gets the value of the telefonnummer property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTelefonnummer() {
                    return telefonnummer;
                }

                /**
                 * Sets the value of the telefonnummer property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTelefonnummer(String value) {
                    this.telefonnummer = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Ort-ID" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
         *         &lt;element name="Ort" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Platz" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="min.Spieleranzahl" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
         *         &lt;element name="max.Spieleranzahl" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
         *         &lt;element name="Oeffnungszeiten">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="geoeffnet_von" type="{http://www.w3.org/2001/XMLSchema}time"/>
         *                   &lt;element name="geoeffnet_bis" type="{http://www.w3.org/2001/XMLSchema}time"/>
         *                   &lt;element name="geschlossen_an" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Preis">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *               &lt;minInclusive value="0"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ortID",
            "ort",
            "platz",
            "minSpieleranzahl",
            "maxSpieleranzahl",
            "oeffnungszeiten",
            "preis"
        })
        public static class Oertlichkeit {

            @XmlElement(name = "Ort-ID", required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger ortID;
            @XmlElement(name = "Ort", required = true)
            protected String ort;
            @XmlElement(name = "Platz", required = true)
            protected String platz;
            @XmlElement(name = "min.Spieleranzahl", required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger minSpieleranzahl;
            @XmlElement(name = "max.Spieleranzahl", required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger maxSpieleranzahl;
            @XmlElement(name = "Oeffnungszeiten", required = true)
            protected Events.Event.Oertlichkeit.Oeffnungszeiten oeffnungszeiten;
            @XmlElement(name = "Preis", required = true)
            protected BigDecimal preis;

            /**
             * Gets the value of the ortID property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getOrtID() {
                return ortID;
            }

            /**
             * Sets the value of the ortID property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setOrtID(BigInteger value) {
                this.ortID = value;
            }

            /**
             * Gets the value of the ort property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrt() {
                return ort;
            }

            /**
             * Sets the value of the ort property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrt(String value) {
                this.ort = value;
            }

            /**
             * Gets the value of the platz property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPlatz() {
                return platz;
            }

            /**
             * Sets the value of the platz property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPlatz(String value) {
                this.platz = value;
            }

            /**
             * Gets the value of the minSpieleranzahl property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getMinSpieleranzahl() {
                return minSpieleranzahl;
            }

            /**
             * Sets the value of the minSpieleranzahl property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setMinSpieleranzahl(BigInteger value) {
                this.minSpieleranzahl = value;
            }

            /**
             * Gets the value of the maxSpieleranzahl property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getMaxSpieleranzahl() {
                return maxSpieleranzahl;
            }

            /**
             * Sets the value of the maxSpieleranzahl property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setMaxSpieleranzahl(BigInteger value) {
                this.maxSpieleranzahl = value;
            }

            /**
             * Gets the value of the oeffnungszeiten property.
             * 
             * @return
             *     possible object is
             *     {@link Events.Event.Oertlichkeit.Oeffnungszeiten }
             *     
             */
            public Events.Event.Oertlichkeit.Oeffnungszeiten getOeffnungszeiten() {
                return oeffnungszeiten;
            }

            /**
             * Sets the value of the oeffnungszeiten property.
             * 
             * @param value
             *     allowed object is
             *     {@link Events.Event.Oertlichkeit.Oeffnungszeiten }
             *     
             */
            public void setOeffnungszeiten(Events.Event.Oertlichkeit.Oeffnungszeiten value) {
                this.oeffnungszeiten = value;
            }

            /**
             * Gets the value of the preis property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPreis() {
                return preis;
            }

            /**
             * Sets the value of the preis property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setPreis(BigDecimal value) {
                this.preis = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="geoeffnet_von" type="{http://www.w3.org/2001/XMLSchema}time"/>
             *         &lt;element name="geoeffnet_bis" type="{http://www.w3.org/2001/XMLSchema}time"/>
             *         &lt;element name="geschlossen_an" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "geoeffnetVon",
                "geoeffnetBis",
                "geschlossenAn"
            })
            public static class Oeffnungszeiten {

                @XmlElement(name = "geoeffnet_von", required = true)
                @XmlSchemaType(name = "time")
                protected XMLGregorianCalendar geoeffnetVon;
                @XmlElement(name = "geoeffnet_bis", required = true)
                @XmlSchemaType(name = "time")
                protected XMLGregorianCalendar geoeffnetBis;
                @XmlElement(name = "geschlossen_an", required = true)
                protected String geschlossenAn;

                /**
                 * Gets the value of the geoeffnetVon property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getGeoeffnetVon() {
                    return geoeffnetVon;
                }

                /**
                 * Sets the value of the geoeffnetVon property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setGeoeffnetVon(XMLGregorianCalendar value) {
                    this.geoeffnetVon = value;
                }

                /**
                 * Gets the value of the geoeffnetBis property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getGeoeffnetBis() {
                    return geoeffnetBis;
                }

                /**
                 * Sets the value of the geoeffnetBis property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setGeoeffnetBis(XMLGregorianCalendar value) {
                    this.geoeffnetBis = value;
                }

                /**
                 * Gets the value of the geschlossenAn property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getGeschlossenAn() {
                    return geschlossenAn;
                }

                /**
                 * Sets the value of the geschlossenAn property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setGeschlossenAn(String value) {
                    this.geschlossenAn = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Spieler" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Anzeigename" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Telefonnummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "spieler"
        })
        public static class Spielerliste {

            @XmlElement(name = "Spieler", required = true)
            protected List<Events.Event.Spielerliste.Spieler> spieler;

            /**
             * Gets the value of the spieler property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the spieler property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSpieler().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Events.Event.Spielerliste.Spieler }
             * 
             * 
             */
            public List<Events.Event.Spielerliste.Spieler> getSpieler() {
                if (spieler == null) {
                    spieler = new ArrayList<Events.Event.Spielerliste.Spieler>();
                }
                return this.spieler;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Anzeigename" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Telefonnummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "anzeigename",
                "telefonnummer"
            })
            public static class Spieler {

                @XmlElement(name = "Anzeigename", required = true)
                protected String anzeigename;
                @XmlElement(name = "Telefonnummer", required = true)
                protected String telefonnummer;

                /**
                 * Gets the value of the anzeigename property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAnzeigename() {
                    return anzeigename;
                }

                /**
                 * Sets the value of the anzeigename property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAnzeigename(String value) {
                    this.anzeigename = value;
                }

                /**
                 * Gets the value of the telefonnummer property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTelefonnummer() {
                    return telefonnummer;
                }

                /**
                 * Sets the value of the telefonnummer property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTelefonnummer(String value) {
                    this.telefonnummer = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="von" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="bis" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "von",
            "bis"
        })
        public static class Spielzeitraum {

            @XmlElement(required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar von;
            @XmlElement(required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar bis;

            /**
             * Gets the value of the von property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getVon() {
                return von;
            }

            /**
             * Sets the value of the von property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setVon(XMLGregorianCalendar value) {
                this.von = value;
            }

            /**
             * Gets the value of the bis property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getBis() {
                return bis;
            }

            /**
             * Sets the value of the bis property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setBis(XMLGregorianCalendar value) {
                this.bis = value;
            }

        }

    }

}
