//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.27 at 11:45:22 AM MESZ 
//


package jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Orteliste_QNAME = new QName("", "Orteliste");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrteType }
     * 
     */
    public OrteType createOrteType() {
        return new OrteType();
    }

    /**
     * Create an instance of {@link OType }
     * 
     */
    public OType createOType() {
        return new OType();
    }

    /**
     * Create an instance of {@link OType.Oeffnungszeiten }
     * 
     */
    public OType.Oeffnungszeiten createOTypeOeffnungszeiten() {
        return new OType.Oeffnungszeiten();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrteType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Orteliste")
    public JAXBElement<OrteType> createOrteliste(OrteType value) {
        return new JAXBElement<OrteType>(_Orteliste_QNAME, OrteType.class, null, value);
    }

}
