//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.21 at 11:53:42 AM MESZ 
//


package jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Events.Event }
     * 
     */
    public Events.Event createEventsEvent() {
        return new Events.Event();
    }

    /**
     * Create an instance of {@link Events.Event.Admin }
     * 
     */
    public Events.Event.Admin createEventsEventAdmin() {
        return new Events.Event.Admin();
    }

    /**
     * Create an instance of {@link Events.Event.Backlist }
     * 
     */
    public Events.Event.Backlist createEventsEventBacklist() {
        return new Events.Event.Backlist();
    }

    /**
     * Create an instance of {@link Events.Event.Backlist.Spieler }
     * 
     */
    public Events.Event.Backlist.Spieler createEventsEventBacklistSpieler() {
        return new Events.Event.Backlist.Spieler();
    }

    /**
     * Create an instance of {@link Events.Event.Oertlichkeit }
     * 
     */
    public Events.Event.Oertlichkeit createEventsEventOertlichkeit() {
        return new Events.Event.Oertlichkeit();
    }

    /**
     * Create an instance of {@link Events.Event.Oertlichkeit.Oeffnungszeiten }
     * 
     */
    public Events.Event.Oertlichkeit.Oeffnungszeiten createEventsEventOertlichkeitOeffnungszeiten() {
        return new Events.Event.Oertlichkeit.Oeffnungszeiten();
    }

    /**
     * Create an instance of {@link Events.Event.Spielerliste }
     * 
     */
    public Events.Event.Spielerliste createEventsEventSpielerliste() {
        return new Events.Event.Spielerliste();
    }

    /**
     * Create an instance of {@link Events }
     * 
     */
    public Events createEvents() {
        return new Events();
    }

    /**
     * Create an instance of {@link Events.Event.Spielerliste.Spieler }
     * 
     */
    public Events.Event.Spielerliste.Spieler createEventsEventSpielerlisteSpieler() {
        return new Events.Event.Spielerliste.Spieler();
    }

    /**
     * Create an instance of {@link Events.Event.Spielzeitraum }
     * 
     */
    public Events.Event.Spielzeitraum createEventsEventSpielzeitraum() {
        return new Events.Event.Spielzeitraum();
    }

}
