//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.18 at 11:51:24 AM MESZ 
//


package jaxb;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ort" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Ort-ID" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                   &lt;element name="Ort" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Platz" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="min.Spieleranzahl" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                   &lt;element name="max.Spieleranzahl" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                   &lt;element name="Oeffnungszeiten">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="geoeffnet_von" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *                             &lt;element name="geoeffnet_bis" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *                             &lt;element name="geschlossen_an" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Preis">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;minInclusive value="0"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ort"
})
@XmlRootElement(name = "Orteliste")
public class Orteliste {

    @XmlElement(name = "Ort", required = true)
    protected List<Orteliste.Ort> ort;

    /**
     * Gets the value of the ort property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ort property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Orteliste.Ort }
     * 
     * 
     */
    public List<Orteliste.Ort> getOrt() {
        if (ort == null) {
            ort = new ArrayList<Orteliste.Ort>();
        }
        return this.ort;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Ort-ID" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *         &lt;element name="Ort" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Platz" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="min.Spieleranzahl" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *         &lt;element name="max.Spieleranzahl" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *         &lt;element name="Oeffnungszeiten">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="geoeffnet_von" type="{http://www.w3.org/2001/XMLSchema}time"/>
     *                   &lt;element name="geoeffnet_bis" type="{http://www.w3.org/2001/XMLSchema}time"/>
     *                   &lt;element name="geschlossen_an" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Preis">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;minInclusive value="0"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ortID",
        "ort",
        "platz",
        "minSpieleranzahl",
        "maxSpieleranzahl",
        "oeffnungszeiten",
        "preis"
    })
    public static class Ort {

        @XmlElement(name = "Ort-ID", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger ortID;
        @XmlElement(name = "Ort", required = true)
        protected String ort;
        @XmlElement(name = "Platz", required = true)
        protected String platz;
        @XmlElement(name = "min.Spieleranzahl", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger minSpieleranzahl;
        @XmlElement(name = "max.Spieleranzahl", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger maxSpieleranzahl;
        @XmlElement(name = "Oeffnungszeiten", required = true)
        protected Orteliste.Ort.Oeffnungszeiten oeffnungszeiten;
        @XmlElement(name = "Preis", required = true)
        protected BigDecimal preis;

        /**
         * Gets the value of the ortID property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getOrtID() {
            return ortID;
        }

        /**
         * Sets the value of the ortID property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setOrtID(BigInteger value) {
            this.ortID = value;
        }

        /**
         * Gets the value of the ort property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrt() {
            return ort;
        }

        /**
         * Sets the value of the ort property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrt(String value) {
            this.ort = value;
        }

        /**
         * Gets the value of the platz property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlatz() {
            return platz;
        }

        /**
         * Sets the value of the platz property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlatz(String value) {
            this.platz = value;
        }

        /**
         * Gets the value of the minSpieleranzahl property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getMinSpieleranzahl() {
            return minSpieleranzahl;
        }

        /**
         * Sets the value of the minSpieleranzahl property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setMinSpieleranzahl(BigInteger value) {
            this.minSpieleranzahl = value;
        }

        /**
         * Gets the value of the maxSpieleranzahl property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getMaxSpieleranzahl() {
            return maxSpieleranzahl;
        }

        /**
         * Sets the value of the maxSpieleranzahl property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setMaxSpieleranzahl(BigInteger value) {
            this.maxSpieleranzahl = value;
        }

        /**
         * Gets the value of the oeffnungszeiten property.
         * 
         * @return
         *     possible object is
         *     {@link Orteliste.Ort.Oeffnungszeiten }
         *     
         */
        public Orteliste.Ort.Oeffnungszeiten getOeffnungszeiten() {
            return oeffnungszeiten;
        }

        /**
         * Sets the value of the oeffnungszeiten property.
         * 
         * @param value
         *     allowed object is
         *     {@link Orteliste.Ort.Oeffnungszeiten }
         *     
         */
        public void setOeffnungszeiten(Orteliste.Ort.Oeffnungszeiten value) {
            this.oeffnungszeiten = value;
        }

        /**
         * Gets the value of the preis property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPreis() {
            return preis;
        }

        /**
         * Sets the value of the preis property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPreis(BigDecimal value) {
            this.preis = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="geoeffnet_von" type="{http://www.w3.org/2001/XMLSchema}time"/>
         *         &lt;element name="geoeffnet_bis" type="{http://www.w3.org/2001/XMLSchema}time"/>
         *         &lt;element name="geschlossen_an" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "geoeffnetVon",
            "geoeffnetBis",
            "geschlossenAn"
        })
        public static class Oeffnungszeiten {

            @XmlElement(name = "geoeffnet_von", required = true)
            @XmlSchemaType(name = "time")
            protected XMLGregorianCalendar geoeffnetVon;
            @XmlElement(name = "geoeffnet_bis", required = true)
            @XmlSchemaType(name = "time")
            protected XMLGregorianCalendar geoeffnetBis;
            @XmlElement(name = "geschlossen_an", required = true)
            protected String geschlossenAn;

            /**
             * Gets the value of the geoeffnetVon property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getGeoeffnetVon() {
                return geoeffnetVon;
            }

            /**
             * Sets the value of the geoeffnetVon property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setGeoeffnetVon(XMLGregorianCalendar value) {
                this.geoeffnetVon = value;
            }

            /**
             * Gets the value of the geoeffnetBis property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getGeoeffnetBis() {
                return geoeffnetBis;
            }

            /**
             * Sets the value of the geoeffnetBis property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setGeoeffnetBis(XMLGregorianCalendar value) {
                this.geoeffnetBis = value;
            }

            /**
             * Gets the value of the geschlossenAn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGeschlossenAn() {
                return geschlossenAn;
            }

            /**
             * Sets the value of the geschlossenAn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGeschlossenAn(String value) {
                this.geschlossenAn = value;
            }

        }

    }

}
