//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.08 at 02:23:42 PM MESZ 
//


package jaxb;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for oType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="oType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Platz" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="min.Spieleranzahl" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="max.Spieleranzahl" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="Preis">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "oType", propOrder = {
    "platz",
    "minSpieleranzahl",
    "maxSpieleranzahl",
    "preis"
})
public class OType {

    @XmlElement(name = "Platz", required = true)
    protected String platz;
    @XmlElement(name = "min.Spieleranzahl", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger minSpieleranzahl;
    @XmlElement(name = "max.Spieleranzahl", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger maxSpieleranzahl;
    @XmlElement(name = "Preis", required = true)
    protected BigDecimal preis;

    /**
     * Gets the value of the platz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatz() {
        return platz;
    }

    /**
     * Sets the value of the platz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatz(String value) {
        this.platz = value;
    }

    /**
     * Gets the value of the minSpieleranzahl property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinSpieleranzahl() {
        return minSpieleranzahl;
    }

    /**
     * Sets the value of the minSpieleranzahl property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinSpieleranzahl(BigInteger value) {
        this.minSpieleranzahl = value;
    }

    /**
     * Gets the value of the maxSpieleranzahl property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxSpieleranzahl() {
        return maxSpieleranzahl;
    }

    /**
     * Sets the value of the maxSpieleranzahl property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxSpieleranzahl(BigInteger value) {
        this.maxSpieleranzahl = value;
    }

    /**
     * Gets the value of the preis property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPreis() {
        return preis;
    }

    /**
     * Sets the value of the preis property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPreis(BigDecimal value) {
        this.preis = value;
    }

}
