//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.08 at 02:23:42 PM MESZ 
//


package jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for slType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="slType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Spieler" type="{}spielerType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="min.Spieler" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="max.Spieler" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "slType", propOrder = {
    "spieler"
})
public class SlType {

    @XmlElement(name = "Spieler", required = true)
    protected SpielerType spieler;
    @XmlAttribute(name = "min.Spieler")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger minSpieler;
    @XmlAttribute(name = "max.Spieler")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger maxSpieler;

    /**
     * Gets the value of the spieler property.
     * 
     * @return
     *     possible object is
     *     {@link SpielerType }
     *     
     */
    public SpielerType getSpieler() {
        return spieler;
    }

    /**
     * Sets the value of the spieler property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpielerType }
     *     
     */
    public void setSpieler(SpielerType value) {
        this.spieler = value;
    }

    /**
     * Gets the value of the minSpieler property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinSpieler() {
        return minSpieler;
    }

    /**
     * Sets the value of the minSpieler property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinSpieler(BigInteger value) {
        this.minSpieler = value;
    }

    /**
     * Gets the value of the maxSpieler property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxSpieler() {
        return maxSpieler;
    }

    /**
     * Sets the value of the maxSpieler property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxSpieler(BigInteger value) {
        this.maxSpieler = value;
    }

}
